### ISSUE TITLE
[MESH] Multiple PTS dongle tests issue

### ISSUE THREAD

**Issue by kolodgrz** [intel/auto-pts#170]
Currently there is no clear way how to handle multiple PTS dongle test cases.

Bluetooth erratas:
CASE0038577, CASE0038579

**Comment by tedd-an** [comment]
@kolodgrz I think this is resolved, right?

**Comment by kolodgrz** [comment]
@tedd-an This is outdated - we can close it. Currently we have slightly different approach on multiple dongle testing. Previously we supposed that one automation PTS daemon will handle mutliple test cases. Now we run every test case on seperate machine (autopts server).

**Comment by tedd-an** [comment]
Close the issue.
