### ISSUE TITLE
[MESH]: Failed to remove address from subscription list

### ISSUE THREAD

**Issue by MariuszSkamra** [intel/auto-pts#188]
I've analyzed this and seems that Friend Subscription List Remove message has been properly sent, however test fails with reason:
"Friendship Subscription List Remove Procedure failed."

Affected TC: MESH/NODE/TNPT/BV-05-C

PTS issue: CASE0041830

**Comment by sjanc** [comment]
is this stil an issue with latest PTS?

**Comment by KKopyscinski** [comment]
@sjanc  As of PTS 8.0.3 MESH/NODE/TNPT/BV-05-C is passing. (tested on NimBLE)

**Comment by michal-narajowski** [comment]
Works on Zephyr too. Closing.
