### ISSUE TITLE
[MESH Maintenance] MESH/NODE/CFG/HBS/BV-01-C [Receive Config Heartbeat Subscription Set/Get message] test case failure

### ISSUE THREAD

**Issue by kolodgrz** [intel/auto-pts#215]
Test is failing because of wrong returned MinHop value (0x7F instead of 0x00) in heartbeat subscription status.

MESH TS 1.0.2 says:
"5. Repeat step 1, but with Destination field set to the unassigned address 0x0000, and the
PeriodLog field set to 0x10.
6. The Lower Tester expects the IUT to respond with a Config Heartbeat Subscription Status
message with the Status field set to 0x00, the Source and Destination fields set to the unassigned
address 0x0000, the MinHops field set to 0x7F, and the CountLog, PeriodLog and MaxHops
fields set to 0x00."

but MESH Profile spec says:
"When the Heartbeat Subscription Source state or the Heartbeat Subscription Destination state is set to the unassigned address, the value of the Source and Destination fields of the Config Heartbeat Subscription Status message shall be set to the unassigned address and the values of the CountLog, PeriodLog, MinHops, and MaxHops fields shall be set to 0x00."

Currently PTS expects MinHops value as 0x00 (as MESH Profile says) but TS says 0x7F (changed from 0x00 in TS 1.0.1 -> 1.0.2).

[TSE 11015](https://www.bluetooth.org/tse/errata_view.cfm?errata_id=11015) reported.

**Comment by tedd-an** [comment]
No more reproduce the issue.
