### ISSUE TITLE
[GATT] Add discover all procedure

### ISSUE THREAD

**Issue by MariuszSkamra** [intel/auto-pts#220]
Add test cases related to this one when https://github.com/zephyrproject-rtos/zephyr/pull/9986 will be merged

**Comment by tedd-an** [comment]
@MariuszSkamra If this is done, please close the issue. 

Thanks

**Comment by MariuszSkamra** [comment]
Assigned to @szymon-czapracki

**Comment by MariuszSkamra** [comment]
resolved in 25b450c33a135fdd67161c7206fc31ec26861c4a
