### ISSUE TITLE
[Week 40 Maintenance] Implement missing test cases

### ISSUE THREAD

**Issue by kolodgrz** [intel/auto-pts#223]
Implement missing automation test cases:
GAP/BROB/BCST/BV-05-C
GAP/CONN/ACEP/BV-03-C
GAP/CONN/ACEP/BV-04-C
GAP/CONN/GCEP/BV-05-C
GAP/CONN/GCEP/BV-06-C
GAP/CONN/CPUP/BV-06-C
GAP/BOND/BON/BV-04-C
GAP/ADV/BV-17-C

**Comment by tedd-an** [comment]
These tests are implemented:
GAP/CONN/ACEP/BV-03-C
GAP/CONN/ACEP/BV-04-C
GAP/CONN/GCEP/BV-05-C
GAP/CONN/GCEP/BV-06-C
GAP/BOND/BON/BV-04-C

And these are not implemented:
**GAP/BROB/BCST/BV-05-C
GAP/CONN/CPUP/BV-06-C
GAP/ADV/BV-17-C**

**Comment by MariuszSkamra** [comment]
Looks like it's already resolved
 52/532   GAP     GAP/CONN/CPUP/BV-06-C         PASS            24.433                  
 99/532   GAP     GAP/ADV/BV-17-C               PASS            18.034                  

Closing since there is no  GAP/BROB/BCST/BV-05-C in the current test plan
