### ISSUE TITLE
auto-pts client with QEMU DUT blocks

### ISSUE THREAD

**Issue by rmstoi** [intel/auto-pts#225]
Running auto-pts client with QEMU DUT blocks for some test cases. This causes the issue that test round cannot be completed with QEMU. For example this GAP test cases blocks.

./autoptsclient-zephyr.py zephyr-hci ./zephyr.elf -i 10.0.0.1 -c GAP/BROB/BCST/BV-03-C

It blocks at:

pybtp/iutctl_common.py

```
        if self._rx_worker.is_alive():
            self._rx_worker.join()
```
It seems in this case QEMU is crashing (Zephyr BT issue?). Log file attached.

[iut-zephyr.log](https://github.com/otcshare/auto-pts/files/2547786/iut-zephyr.log)

**Comment by mkasenberg** [comment]
@michal-narajowski, tested, the issue no longer appears.
