### ISSUE TITLE
[MESH] BTP_ERROR - MESH/NODE/TNPT/BV-05-C

### ISSUE THREAD

**Issue by tedd-an** [intel/auto-pts#259]
PTS version: 7.4.1
Interop.PTSControl.dll - old version by reverting the patch 8d03da0

Test Case:
MESH/NODE/TNPT/BV-05-C

Error:
BTP ERROR

Description:
Send a Segmented Access Message - Group/Virtual Address

Log:
[MESH_MESH_NODE_TNPT_BV-05-C_2019-03-26T01-24-15-631337.log](https://github.com/intel/auto-pts/files/3010500/MESH_MESH_NODE_TNPT_BV-05-C_2019-03-26T01-24-15-631337.log)
[MESH_MESH_NODE_TNPT_BV-05-C_2019-03-26T01-27-28-268562.log](https://github.com/intel/auto-pts/files/3010501/MESH_MESH_NODE_TNPT_BV-05-C_2019-03-26T01-27-28-268562.log)
[MESH_MESH_NODE_TNPT_BV-05-C_2019-03-26T01-30-46-273182.log](https://github.com/intel/auto-pts/files/3010502/MESH_MESH_NODE_TNPT_BV-05-C_2019-03-26T01-30-46-273182.log)
[MESH_MESH_NODE_TNPT_BV-05-C.log](https://github.com/intel/auto-pts/files/3010503/MESH_MESH_NODE_TNPT_BV-05-C.log)

**Comment by sjanc** [comment]
I think this is passing now both on Zephyr and Mynewt.
