### ISSUE TITLE
[GAP] INCONC - GAP/BROB/BCST/BV-03-C

### ISSUE THREAD

**Issue by tedd-an** [intel/auto-pts#280]
PTS version: 7.4.1
Interop.PTSControl.dll - old version by reverting the patch 8d03da0

Test Case:
GAP/BROB/BCST/BV-03-C

Error:
INCONC

Description:
Verify the IUT in Broadcast Mode using a resolvable private address.

Log:
[GAP_GAP_BROB_BCST_BV-03-C_2019-03-25T19-55-41-403619.log](https://github.com/intel/auto-pts/files/3010769/GAP_GAP_BROB_BCST_BV-03-C_2019-03-25T19-55-41-403619.log)
[GAP_GAP_BROB_BCST_BV-03-C_2019-03-25T19-56-41-652662.log](https://github.com/intel/auto-pts/files/3010770/GAP_GAP_BROB_BCST_BV-03-C_2019-03-25T19-56-41-652662.log)
[GAP_GAP_BROB_BCST_BV-03-C_2019-03-25T19-57-41-987695.log](https://github.com/intel/auto-pts/files/3010771/GAP_GAP_BROB_BCST_BV-03-C_2019-03-25T19-57-41-987695.log)
[GAP_GAP_BROB_BCST_BV-03-C.log](https://github.com/intel/auto-pts/files/3010772/GAP_GAP_BROB_BCST_BV-03-C.log)

**Comment by MariuszSkamra** [comment]
fixed with https://github.com/intel/auto-pts/pull/305
