### ISSUE TITLE
[GAP] INCONC - GAP/CONN/UCON/BV-06-C

### ISSUE THREAD

**Issue by tedd-an** [intel/auto-pts#286]
PTS version: 7.4.1
Interop.PTSControl.dll - old version by reverting the patch 8d03da0

Test Case:
GAP/CONN/UCON/BV-06-C

Error:
INCONC

Description:
Verify the IUT in the Undirected Connectable Mode using Resolvable Private Address can connect with another device performing the General Connection Establishment Procedure.

Log:
[GAP_GAP_CONN_UCON_BV-06-C_2019-03-25T19-47-38-443197.log](https://github.com/intel/auto-pts/files/3010819/GAP_GAP_CONN_UCON_BV-06-C_2019-03-25T19-47-38-443197.log)
[GAP_GAP_CONN_UCON_BV-06-C_2019-03-25T19-48-41-050148.log](https://github.com/intel/auto-pts/files/3010820/GAP_GAP_CONN_UCON_BV-06-C_2019-03-25T19-48-41-050148.log)
[GAP_GAP_CONN_UCON_BV-06-C_2019-03-25T19-49-42-811004.log](https://github.com/intel/auto-pts/files/3010821/GAP_GAP_CONN_UCON_BV-06-C_2019-03-25T19-49-42-811004.log)
[GAP_GAP_CONN_UCON_BV-06-C.log](https://github.com/intel/auto-pts/files/3010822/GAP_GAP_CONN_UCON_BV-06-C.log)

**Comment by MariuszSkamra** [comment]
PTS issue created CASE0054758, I will push the updated version of this test case to use wid handler instead of scripted test case steps.

**Comment by tedd-an** [comment]
This started to pass last 10 runnings.
Close for now and reopen if it starts to fail again.
