### ISSUE TITLE
[MESH] MESH/NODE/PROV/BV-10-C - FAIL

### ISSUE THREAD

**Issue by tedd-an** [intel/auto-pts#297]
PTS version: 7.4.1
Interop.PTSControl.dll - old version by reverting the patch 8d03da0

Test Case:
MESH/NODE/PROV/BV-10-C

Error:
FAIL

[MESH_MESH_NODE_PROV_BV-10-C.log](https://github.com/intel/auto-pts/files/3048991/MESH_MESH_NODE_PROV_BV-10-C.log)
[MESH_MESH_NODE_PROV_BV-10-C_2019-04-04T22-47-48-044498.log](https://github.com/intel/auto-pts/files/3048992/MESH_MESH_NODE_PROV_BV-10-C_2019-04-04T22-47-48-044498.log)
[MESH_MESH_NODE_PROV_BV-10-C_2019-04-04T22-49-03-446622.log](https://github.com/intel/auto-pts/files/3048993/MESH_MESH_NODE_PROV_BV-10-C_2019-04-04T22-49-03-446622.log)

**Comment by MariuszSkamra** [comment]
Got this test case passing:
291/532   MESH    MESH/NODE/PROV/BV-10-C        PASS            52.014           

I saw this was passing for you as well in Bluetooth test session - WW31.2
