### ISSUE TITLE
[MESH] MESH/NODE/MPS/BV-10-C causes XML-RPC ERROR

### ISSUE THREAD

**Issue by tedd-an** [intel/auto-pts#321]
MESH/NODE/MPS/BV-10-C causes XML-RPC ERROR and it blocks the rest of test.

git bisect pointed this patch:
https://github.com/zephyrproject-rtos/zephyr/commit/2699d05e45f58897edd7d6d3718c254224390667

restart the pts didn't fix the issue.

From the failure log, there is a missing events from the BTP.
Pass log
[autoptsclient-zephyr.pass.log](https://github.com/intel/auto-pts/files/3267764/autoptsclient-zephyr.pass.log)
Failure log
[autoptsclient-zephyr.fail.log](https://github.com/intel/auto-pts/files/3267763/autoptsclient-zephyr.fail.log)

PTS logs
[MESH_NODE_MPS_BV_10_C.zip](https://github.com/intel/auto-pts/files/3267762/MESH_NODE_MPS_BV_10_C.zip)

**Comment by MariuszSkamra** [comment]
1/1   MESH   MESH/NODE/MPS/BV-10-C   PASS            31.367                  

fixed by https://github.com/zephyrproject-rtos/zephyr/pull/16820
