### ISSUE TITLE
[README] Mention about autopts Slack channel 

### ISSUE THREAD

**Issue by MariuszSkamra** [intel/auto-pts#335]

**Comment by GuptaTanisha** [comment]
Please assign this to me.

**Comment by GuptaTanisha** [comment]
@michal-narajowski Can you share the link of Slack Channel?

**Comment by michal-narajowski** [comment]
This is the invite link to Zephyr slack workspace: https://join.slack.com/t/zephyrproject/shared_invite/zt-953wf991-q7qw_houhNJrwT~Ac1TJEg
Slack channel is `#auto-pts`.

**Comment by michal-narajowski** [comment]
Turns out there is a direct link to the #auto-pts channel: https://zephyrproject.slack.com/archives/CG1N5KGUT
