### ISSUE TITLE
Add handing new wid 132 

### ISSUE THREAD

**Issue by agata-ponitka** [intel/auto-pts#361]
PTS expect IUT service changed and use to it wid 132 "Please change IUT's GATT database by adding or removing services and/or characteristics. Click OK after committing the database change."
Auto-pts sends  gatts_add_svc 0 'AA50' and BTTester on Zephyr side does not handle this correctly. 
Consider changes here or on BTTester (Zephyr issue might be required)

**Comment by sjanc** [comment]
fixed
