### ISSUE TITLE
TypeError: super() argument 1 must be type, not classobj in ptscontrol.py 

### ISSUE THREAD

**Issue by jsplyy** [intel/auto-pts#368]
When I try to run autopts.py with pyhton2.7
This error occured.

It is caused by parent does not inherit from object.

I check win32com.server.connect.ConnectableServer class in C:\Python27\Lib\site-packages\win32com\server\connect.py file.

sure that It does not inherit from the class, like ClassA(object)

So, is it a mistake, and need to remove super() in __init__()?

![image](https://user-images.githubusercontent.com/3600912/76336288-beddac00-6330-11ea-86ee-757ff10e2b6d.png)
![image](https://user-images.githubusercontent.com/3600912/76336530-1b40cb80-6331-11ea-8cda-5ddd4bca5caf.png)

**Comment by mkasenberg** [comment]
@sjanc , python versions <3 are no more supported
