### ISSUE TITLE
secure connection test cases automation

### ISSUE THREAD

**Issue by jsplyy** [intel/auto-pts#394]
@michal-narajowski @carlescufi 

The PTS dongle support Bluetooth 4.2 
and I try to add secure connection cases like SM/MAS/SCJW/BV-01-C in "auto-pts\ptsprojects\zephyr\sm.py", which could pass automatically.

        ZTestCase("SM", "SM/MAS/SCJW/BV-01-C",
                  pre_conditions +
                  [TestFunc(btp.gap_set_io_cap, IOCap.display_only),
                  TestFunc(btp.gap_set_bondable_off),
                  ],
                  generic_wid_hdl=sm_wid_hdl),

So on my local, all the secure connection test cases could pass automatically with auto-pts, do you know why did not the auto-pts support sc test cases?

If you confirm it works on your side, maybe I could submit one PR for this,

**Comment by MariuszSkamra** [comment]
Feel free to submit PR

**Comment by KKopyscinski** [comment]
@MariuszSkamra I think this can be closed now

**Comment by MariuszSkamra** [comment]
resolved
