### ISSUE TITLE
README: Include invalid link[page not found]

### ISSUE THREAD

**Issue by LingaoM** [intel/auto-pts#462]
# Zephyr with AutoPTS step-by-step setup tutorial
Check out the guide how to set up AutoPTS for Zephyr + nRF52 under:
- Linux + Windows 10 virtual machine

  https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/guides/bluetooth/autopts/autopts-linux.rst

- Windows 10

  https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/guides/bluetooth/autopts/autopts-win10.rst

**Comment by mkasenberg** [comment]
Coming soon :)
https://github.com/zephyrproject-rtos/zephyr/pull/34281
