### ISSUE TITLE
GAP/CONN/NCON/BV-02-C Failed

### ISSUE THREAD

**Issue by LingaoM** [intel/auto-pts#544]
[autopts-iutctl-zephyr.log](https://github.com/intel/auto-pts/files/6999047/autopts-iutctl-zephyr.log)
[GAP_CONN_NCON_BV-02-C_2021_08_16_02_02_41.log](https://github.com/intel/auto-pts/files/6999049/GAP_CONN_NCON_BV-02-C_2021_08_16_02_02_41.log)
[GAP_CONN_NCON_BV_02_C_2021_08_16_17_03_09.zip](https://github.com/intel/auto-pts/files/6999067/GAP_CONN_NCON_BV_02_C_2021_08_16_17_03_09.zip)

**Comment by mkasenberg** [comment]
I can reproduce this fail when missing config overlay with those:
CONFIG_BT_PRIVACY=y
CONFIG_BT_RPA_TIMEOUT=30

**Comment by LingaoM** [comment]
so, we need add this config to dot/zephyr.conf file?

**Comment by mkasenberg** [comment]
I see it is already there in recent version of bot/config.py.zephyr.sample at:
"privacy.conf": {
        "overlay": {
            'CONFIG_BT_PRIVACY': 'y',
             'CONFIG_BT_RPA_TIMEOUT': '30',
         },
        "test_cases": [
            'GAP/PRIV/CONN/BV-10-C',
            'GAP/PRIV/CONN/BV-11-C',
            'GAP/CONN/ACEP/BV-03-C', # As of PTS v7.6.2, not supported
            'GAP/CONN/DCEP/BV-05-C', # As of PTS v7.6.2, not supported
            'GAP/CONN/GCEP/BV-05-C', # As of PTS v7.6.2, not supported
            'GAP/CONN/NCON/BV-02-C',
            'GAP/CONN/UCON/BV-06-C',
            'GAP/BROB/BCST/BV-03-C',
            'GAP/BROB/BCST/BV-04-C',
            'GAP/BROB/OBSV/BV-06-C',
            'GAP/DISC/RPA/BV-01-C',
            'SM/CEN/KDU/BV-05-C',
            'SM/CEN/KDU/BV-10-C',
            'SM/CEN/KDU/BV-11-C',
            'SM/PER/KDU/BV-02-C',
            'SM/PER/KDU/BV-08-C',
        ]
    },

**Comment by sjanc** [comment]
for the record,  we should have tests configuration separated from bot config so that people always run with latest tests settings 

https://github.com/intel/auto-pts/issues/523
https://github.com/intel/auto-pts/pull/557

So hopefully this kind of errors will be reduced once #557 is merged:)

**Comment by sjanc** [comment]
is it fixed now? can this issue be closed?

**Comment by LingaoM** [comment]
Closed
