### ISSUE TITLE
check_args_btpclient_path needed for --btpclientpath argument

### ISSUE THREAD

**Issue by mringwal** [intel/auto-pts#852]
E.g. in `autopts/ptsprojects/bluez/iutclt.py` sets

`CLI_SUPPORT = ['btp_py', 'btpclient_path']`

which causes `cliparser.py` to call `check_args_btpclient_path()`, if --btpclient_path is used, but which doesn't exist and gives an error.

Interestingly, 'btp_py' in CLI_SUPPORT does not allow for additional arguments, but there's a `check_args_btp_py()` function. Could it be that the `btp_py` is a left-over, and it's enough to rename check_args_btp_py into check_args_btpclient_path? While we're looking at this, I guess 'btp_py' could then also be removed from bluez/iutctl.py.

**Comment by mkasenberg** [comment]
Yes, this is a leftover. Back in time btp_py was the name for btpclient_path. The name was confusing, because the btp script of course could be other than .py file.

**Comment by mringwal** [comment]
Would you like me to create a RP for this, or do you want to fix it?

**Comment by mkasenberg** [comment]
I don't have a Bluez environment set up for testing, so I'd appreciate your help, thanks!

**Comment by mringwal** [comment]
Sure. Tested with our btpclient, which is based on the bluez implementation.
